---
title: "p8105_hw2_kr3145"
author: "Kallan Roan"
date: "2025-09-23"
output: github_document
---

Load libraries
```{r}
library(tidyverse)
library(readxl)
```

# Problem 1

Clean pols-month.csv

```{r}
pols_month_df = 
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(
    mon, into = c("year", "month", "day"), sep = "-", convert = TRUE
    ) |>
  mutate(
    month = month.name[month]
  ) |> 
  pivot_longer(
    cols = starts_with("prez"),
    names_to = "president",
    values_to = "president_values",
    names_prefix = "prez_" 
  ) |> 
  filter(president_values == 1) |> 
  select(-day, -president_values) 
```
Clean snp.csv

```{r}
snp_df = 
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(
    date, into = c("month", "day", "year"), sep = "/", convert = TRUE
  ) |> 
  mutate(
    year = ifelse(year <= 15, year + 2000, year + 1900)
  ) |> 
  select(year, month, close, -day) |> 
  arrange(year, month) |> 
  mutate(
    month = month.name[month]
  )
```
Clean unemployment.csv

```{r}
unemployment_df = 
  read_csv("data/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "percent_unemployed"
  ) |> 
  mutate(
    month = month.name[match(toupper(month), toupper(month.abb))]
  )

```

Merge pols_month_df, snp_df, and unemployment_df

```{r}
# join datasets
snp_pols_unempl_df =
  left_join(pols_month_df, snp_df, by = c("year", "month")) |> 
  left_join(unemployment_df, by = c("year", "month")) 
```

PARAGRAPH ABOUT DESCRIPTION HERE





