p8105_hw2_kr3145
================
Kallan Roan
2025-09-23

Load libraries

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

Read and clean pols-month.csv

``` r
pols_month_df = 
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(
    mon, into = c("year", "month", "day"), sep = "-", convert = TRUE
    ) |>
  mutate(month = month.name[month]) |> 
  pivot_longer(
    cols = starts_with("prez"),
    names_to = "president",
    values_to = "president_values",
    names_prefix = "prez_" 
  ) |> 
  filter(president_values == 1) |> 
  select(-day, -president_values) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Read and clean snp.csv

``` r
snp_df = 
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(
    date, into = c("month", "day", "year"), sep = "/", convert = TRUE
  ) |> 
  mutate(
    year = ifelse(year <= 15, year + 2000, year + 1900)
  ) |> 
  select(year, month, close, -day) |> 
  arrange(year, month) |> 
  mutate(
    month = month.name[month]
  )
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Read and clean unemployment.csv

``` r
unemployment_df = 
  read_csv("data/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "percent_unemployed"
  ) |> 
  mutate(
    month = month.name[match(toupper(month), toupper(month.abb))]
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Merge pols_month_df, snp_df, and unemployment_df

``` r
# join datasets
pols_snp_unempl_df =
  left_join(pols_month_df, snp_df, by = c("year", "month")) |> 
  left_join(unemployment_df, by = c("year", "month"))
```

`pols_month_df` from pols-month.csv contains the number of national
politicians who are democratic or republican at any given time. `snp_df`
from snp.csv contains contains information about the Standard & Poor’s
stock market index (S&P), which is used as a representative measure of
stock market as a whole. `unemployment_df` from unemployment.csv
contains monthly percentage of unemployment for the associated year.
After tidying and merging the above datasets, the resulting dataset,
`pols_snp_unempl_df` contains 817 observations and 11 variables. The
dataset represents the years ranging from 1947 to 2015.

`gov_gop`, `sen_gop`, and `rep_gop` represents the number of governors,
senators, and representatives in the republican party on the associated
date. `gov_dem`, `sen_dem`, and `rep_dem` represents the number of
governors, senators, and representatives in the democratic party during
the associated date. `president` indicates whether the president was
republican or democratic during the associated date. `close` represents
the closing values of the S&P stock index on the associated date.
`percent_unemployed` represents the percentage of unemployment during
the associated date.

# Problem 2

Read and clean Mr. Trash Wheel dataset

``` r
mr_trash_wheel_df =
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Mr. Trash Wheel",
             skip = 1) |> 
  janitor::clean_names() |> 
  janitor::remove_empty("cols") |> 
  drop_na(dumpster) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "mr"
  )
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

Read and clean Professor Trash Wheel dataset

``` r
prof_trash_wheel_df =
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Professor Trash Wheel",
             skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    trash_wheel = "prof"
  )
```

Read and clean Gwynnda Trash Wheel dataset

``` r
gwynnda_df =
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", 
             sheet = "Gwynns Falls Trash Wheel",
             skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    trash_wheel = "gwynnda"
  )
```

Bind mr_trash_wheel_df, prof_trash_wheel_df, and gwynnda_df

``` r
all_trash_wheel_df =
  bind_rows(mr_trash_wheel_df, prof_trash_wheel_df, gwynnda_df) |> 
  janitor::clean_names() |> 
  select(dumpster, trash_wheel, everything())
```

The resulting dataset, `all_trash_wheel_df`, has 1188 observations and
15 variables. The dataset represents the years ranging from 2014 to
2025. Some key variables include `weight_tons`, representing the weight
of trash in tons, and `volume_cubic_yards`, representing volume of trash
in cubic yards. There are also other variables representing litter
types, including `plastic_bottles`, `polystyrene`, `cigarette_butts`,
`glass_bottles`, `plastic_bags`, and `wrappers`. `home_powered`
represents the number of homes the amount of trash for the dumpster is
able to power.

The total weight of trash collected by Professor Trash Wheel is 282.26
tons. The total number of cigarette butts collected by Gwynnda in June
of 2022 is 18120.

# Problem 3

Read and clean Zip Codes.csv

``` r
zip_code_df =
  read_csv("data/Zip Codes.csv") |> 
  janitor::clean_names() |> 
  arrange(county, zip_code) |> 
  select(-(state_fips:county_fips), -file_date) 
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Read and clean Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv

``` r
zip_zori_df =
  read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    col = x2015_01_31:x2024_08_31,
    names_to = "date",
    values_to = "zori",
    names_prefix = "x"
  ) |> 
  separate(
    date, into = c("year", "month", "day"), sep = "_", convert = TRUE
  ) |> 
  rename(zip_code = region_name, county = county_name) |> 
  select(county, zip_code, year, month, zori) |> 
  mutate(
    county = str_trim(str_remove(county, "County")),
    month = month.name[month]
  ) |> 
  arrange(county, zip_code) 
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Merge zip_zori_df and zip_code_df

``` r
combined_zip_zori_df =
  left_join(zip_code_df, zip_zori_df, by = c("county", "zip_code")) |> 
  janitor::clean_names()
```

The dataset has 17342 observations and 6 variables. The dataset contains
ZORI calculated by Zillow for the years ranging from 2015 to 2024. There
are 320 unique zip codes and 43 unique neighborhoods in the dataset.

10464, 10474, 10475, 10499, 10550, 10704, 10705, 10803, 11202, 11224,
11239, 11241, 11242, 11243, 11245, 11247, 11251, 11252, 11256, 11693,
10008, 10020, 10041, 10043, 10045, 10047, 10048, 10055, 10072, 10080,
10081, 10082, 10087, 10101, 10102, 10103, 10104, 10105, 10106, 10107,
10108, 10109, 10110, 10111, 10112, 10113, 10114, 10115, 10116, 10117,
10118, 10119, 10120, 10121, 10122, 10123, 10124, 10125, 10126, 10129,
10130, 10131, 10132, 10133, 10138, 10149, 10150, 10151, 10152, 10153,
10154, 10155, 10156, 10157, 10158, 10159, 10160, 10161, 10163, 10164,
10165, 10166, 10167, 10168, 10169, 10170, 10171, 10172, 10173, 10174,
10175, 10176, 10177, 10178, 10179, 10185, 10197, 10199, 10213, 10242,
10249, 10256, 10259, 10260, 10261, 10265, 10268, 10269, 10270, 10271,
10272, 10273, 10274, 10275, 10276, 10277, 10278, 10279, 10281, 10285,
10286, 10292, 10463, 11201, 11001, 11004, 11005, 11040, 11096, 11351,
11352, 11359, 11362, 11363, 11371, 11380, 11381, 11386, 11405, 11411,
11412, 11413, 11414, 11416, 11417, 11419, 11420, 11421, 11422, 11423,
11424, 11425, 11427, 11428, 11429, 11430, 11431, 11433, 11436, 11439,
11451, 11499, 11559, 11580, 11690, 11694, 11695, 11697, 10302, 10307,
10309, 10310, 10311, 10313 are zip codes that appear in the ZIP code
dataset, but do not appear in the Zillow Rental Price dataset. This can
occur because there are certain zip codes that either have low or no
rental housing associated with it, so it cannot produce a reliable ZORI
score. This is because some zip codes cover multiple boroughs and
geographic areas. Some zip codes also cover areas in both NYC and New
York State. For example, 11001 covers Floral Park in Queens and parts of
Nassau County in New York State. This can cause this zip code to not be
included in the zillow dataset. Some zip codes are also associated with
a non-geographic area. More specifically, some zip codes in NYC only
covers a single large address, building complex, businesses, government
offices, or po boxes and not associated with a traditional neighborhood
or borough. For example, 10259 is associated with a single building
under HSBC Bank in Manhattan. Additionally, 11430 is associated with the
JFK airport. Since these locations and may not have a lot of residential
housing associated with it, these zip code won’t be included in zillow.

For all available ZIP codes, compare rental prices in January 2021 to
prices in January 2020. Filter combined_zip_zori_df to only contain
available rental prices in January 2020 and January 2021 for available
zip codes.

``` r
filter_combined_zip_zori_df =
  combined_zip_zori_df |> 
  arrange(zip_code) |> 
  filter(
    month == "January", 
    year %in% c(2020, 2021)
  ) |> #only keep zori scores from January 2020 and 2021
  select(-month) |> #remove month column
  pivot_wider(
    names_from = year,
    values_from = zori
  ) |> 
  drop_na(`2020`, `2021`) |> # drop rows that have NA values in either 2020 or 2021
  mutate(
    difference = `2020` - `2021` # more positive number, larger drop in price
  ) |> 
  arrange(desc(difference)) #|> 
  #head(10) |> 
 # knitr::kable()
```

Make a table that shows the 10 ZIP codes (along with the borough and
neighborhood) with largest drop in price from January 2020 to January
2021.

``` r
filter_combined_zip_zori_df |> 
  head(10) |> 
  knitr::kable()
```

| county   | zip_code | neighborhood                  |     2020 |     2021 | difference |
|:---------|---------:|:------------------------------|---------:|---------:|-----------:|
| New York |    10007 | Lower Manhattan               | 6334.211 | 5421.614 |   912.5966 |
| New York |    10069 | NA                            | 4623.042 | 3874.918 |   748.1245 |
| New York |    10009 | Lower East Side               | 3406.442 | 2692.187 |   714.2550 |
| New York |    10016 | Gramercy Park and Murray Hill | 3731.135 | 3019.431 |   711.7045 |
| New York |    10001 | Chelsea and Clinton           | 4108.098 | 3397.648 |   710.4499 |
| New York |    10002 | Lower East Side               | 3645.416 | 2935.113 |   710.3028 |
| New York |    10004 | Lower Manhattan               | 3149.658 | 2443.697 |   705.9608 |
| New York |    10038 | Lower Manhattan               | 3573.201 | 2875.616 |   697.5853 |
| New York |    10012 | Greenwich Village and Soho    | 3628.566 | 2942.344 |   686.2218 |
| New York |    10010 | Gramercy Park and Murray Hill | 3697.284 | 3012.353 |   684.9304 |

Comment:

After filtering to include zip codes with available rental prices for
both January 2020 and January 2021, the resulting dataset include 82
observations. The `difference` variable is added to represent the ZORI
difference between 2020 to 2021, by calculating ZORI in 2020 minus ZORI
in 2021. This means the more larger and positive the `difference` value
is, the larger the price drop.

The 10 zip codes with the largest drop in price from January 2020 to
January 2021 all reside in Manhattan (New York County), but different
neighborhoods within Manhattan. 10007 had the highest rental price drop
between January 2020 and January 2021 of \$912.597. The top 10 price
drops ranges from \$684.93 to \$912.597.
